cc_library(
    name = "your_code",                     # Namnet på biblioteket, som kan användas i andra byggkonfigurationer
    srcs = ["your_code.cc"],                # Lista över källkodsfiler som ingår i biblioteket
    hdrs = ["your_code.h"],                 # Lista över header-filer som ingår i biblioteket och kan användas av andra moduler
    visibility = ["//visibility:public"],    # Synlighet för biblioteket; här anges att det är offentligt och kan användas av andra paket
)
